import { TestimonialCarousel } from "@/sections/TestimonialsSection/components/TestimonialCarousel";

export const TestimonialsSection = () => {
  return (
    <div className="relative text-sm items-center box-border caret-transparent flex justify-center leading-[20.3px] break-words px-0 py-5 md:text-[17px] md:leading-[24.65px] md:px-5">
      <div className="text-sm box-border caret-transparent grow leading-[20.3px] max-w-[1300px] break-words mx-auto md:text-[17px] md:leading-[24.65px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[20.3px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-figtree before:md:text-[17px] before:md:leading-[24.65px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[20.3px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-figtree after:md:text-[17px] after:md:leading-[24.65px]">
        <div className="text-sm box-border caret-transparent block flex-wrap leading-[20.3px] break-words w-full md:text-[17px] md:flex md:leading-[24.65px]">
          <div className="text-sm box-border caret-transparent clear-both flex grow-0 float-none leading-[20.3px] min-h-px min-w-0 break-words w-full mx-auto md:text-[17px] md:clear-none md:grow md:float-left md:leading-[24.65px] md:min-w-[auto] md:w-6/12 md:mx-0">
            <div className="text-sm box-border caret-transparent flex flex-col grow justify-start leading-[20.3px] max-w-full min-w-px break-words w-full md:text-[17px] md:leading-[24.65px]">
              <div className="text-sm box-border caret-transparent leading-[20.3px] break-words w-full md:text-[17px] md:leading-[24.65px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[20.3px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-figtree before:md:text-[17px] before:md:leading-[24.65px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[20.3px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-figtree after:md:text-[17px] after:md:leading-[24.65px]">
                <div className="text-sm box-border caret-transparent flex flex-col leading-[20.3px] break-words m-5 md:text-[17px] md:leading-[24.65px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[20.3px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-figtree before:md:text-[17px] before:md:leading-[24.65px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[20.3px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-figtree after:md:text-[17px] after:md:leading-[24.65px]">
                  <div className="text-sm box-border caret-transparent leading-[20.3px] break-words text-left md:text-[17px] md:leading-[24.65px]">
                    <div className="text-sm box-border caret-transparent leading-[20.3px] break-words md:text-[17px] md:leading-[24.65px]">
                      <div className="text-sm box-border caret-transparent leading-[20.3px] break-words md:text-[17px] md:leading-[24.65px]">
                        <div className="text-sm box-border caret-transparent leading-[20.3px] break-words md:text-[17px] md:leading-[24.65px]">
                          <h1 className="text-neutral-900 text-4xl italic font-bold box-border caret-transparent clear-both leading-[50.4px] break-words uppercase mb-2.5 font-kanit">
                            Testimonials
                          </h1>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="text-sm box-border caret-transparent leading-[20.3px] break-words md:text-[17px] md:leading-[24.65px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[20.3px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-figtree before:md:text-[17px] before:md:leading-[24.65px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[20.3px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-figtree after:md:text-[17px] after:md:leading-[24.65px]">
                <div className="text-sm box-border caret-transparent leading-[20.3px] break-words m-5 md:text-[17px] md:leading-[24.65px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[20.3px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-figtree before:md:text-[17px] before:md:leading-[24.65px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[20.3px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-figtree after:md:text-[17px] after:md:leading-[24.65px]">
                  <div className="relative text-sm box-border caret-transparent leading-[20.3px] break-words md:text-[17px] md:leading-[24.65px]">
                    <TestimonialCarousel />
                    <div className="absolute text-sm box-border caret-transparent leading-[20.3px] break-words text-center -mt-2.5 top-2/4 inset-x-0 md:text-[17px] md:leading-[24.65px]"></div>
                    <div className="absolute text-sm box-border caret-transparent leading-[20.3px] break-words text-center -mt-2.5 right-0 top-2/4 md:text-[17px] md:leading-[24.65px]"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="text-sm box-border caret-transparent clear-both flex grow-0 float-none leading-[20.3px] min-h-px min-w-0 break-words w-full mx-auto md:text-[17px] md:clear-none md:grow md:float-left md:leading-[24.65px] md:min-w-[auto] md:w-6/12 md:mx-0">
            <div className="text-sm bg-[url('https://c.animaapp.com/mjbg2zzdHx1neY/assets/image0.jpg')] bg-no-repeat bg-cover box-border caret-transparent flex flex-col grow justify-start leading-[20.3px] max-w-full min-h-[500px] min-w-px break-words w-full bg-center m-5 md:text-[17px] md:leading-[24.65px] md:min-h-[auto] md:ml-[100px]"></div>
          </div>
        </div>
      </div>
    </div>
  );
};
